# -*- coding: utf-8 -*-
"""Robot_aspiradora_Depurado.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DZEaLhQEqyGuuUqaxLymTbyuhYrAlNhW

# Robot Aspiradora — Versión depurada
"""

print('Listo: entorno preparado. Si estás en Colab, instala ffmpeg si necesitas guardar video.')

import matplotlib.pyplot as plt
import matplotlib.animation as animation
import numpy as np
import random
from IPython.display import HTML, display

# CORRECCIÓN: Antes el código usaba variables globales definidas con input().

GRID_W = 15
GRID_H = 10
NUM_DIRT = 25
STEPS = 400

random.seed(42)
np.random.seed(42)

class Board:
    def __init__(self, width, height, num_dirt):
        self.width = width
        self.height = height

        self.grid = np.zeros((height, width), dtype=int)

        for _ in range(num_dirt):
            x = random.randrange(width)
            y = random.randrange(height)
            self.grid[y, x] = 1

    def is_dirty(self, x, y):
        return self.grid[y, x] == 1

    def clean(self, x, y):
        self.grid[y, x] = 0

    def dirt_count(self):
        return int(self.grid.sum())


class Robot:
    def __init__(self, board, x=0, y=0):
        self.board = board

        self.x = max(0, min(board.width - 1, x))
        self.y = max(0, min(board.height - 1, y))
        self.cleaned = 0

    def step(self):

        if self.board.is_dirty(self.x, self.y):
            self.board.clean(self.x, self.y)
            self.cleaned += 1
            return

        moves = [(0,1),(0,-1),(1,0),(-1,0)]
        dx, dy = random.choice(moves)
        nx = self.x + dx
        ny = self.y + dy
        if 0 <= nx < self.board.width and 0 <= ny < self.board.height:
            self.x = nx
            self.y = ny


# CORRECCIÓN: encapsulé creación del tablero y robot en una función para facilitar ejecución repetida.
def make_sim(width=GRID_W, height=GRID_H, num_dirt=NUM_DIRT):
    board = Board(width, height, num_dirt)
    # esto inicia el robot en el centro del tablero
    robot = Robot(board, x=width//2, y=height//2)
    return board, robot

# Simulación y animación
import matplotlib.pyplot as plt
import matplotlib.animation as animation
from IPython.display import HTML
import numpy as np

# ===== Aqui configuramos el tablero =====
n = 10
board = np.zeros((n, n))
x, y = 0, 0  # Aqui inicia el robot
trayectoria = [(x, y)]
board[x, y] = 1

# ===== MOVIMIENTO SIMULADO =====
# CORRECCIÓN: antes los datos no eran una secuencia válida (x, y sueltos)
for i in range(1, n):
    trayectoria.append((x, i))
for i in range(1, n):
    trayectoria.append((i, n-1))
for i in range(n-2, -1, -1):
    trayectoria.append((n-1, i))
for i in range(n-2, 0, -1):
    trayectoria.append((i, 0))

# ===== FUNCIÓN DE ANIMACIÓN =====
fig, ax = plt.subplots(figsize=(5, 5))
ax.set_xticks(range(n))
ax.set_yticks(range(n))
ax.set_xlim(-0.5, n-0.5)
ax.set_ylim(-0.5, n-0.5)
ax.grid(True)
ax.set_title("Simulación robot aspiradora")

robot_point, = ax.plot([], [], 'ro', markersize=12)  # CORRECCIÓN: debe ser una secuencia (listas)
path_line, = ax.plot([], [], 'b-', lw=1)

def init():
    robot_point.set_data([], [])
    path_line.set_data([], [])
    return robot_point, path_line

def update(frame):
    x_vals = [p[1] for p in trayectoria[:frame+1]]
    y_vals = [p[0] for p in trayectoria[:frame+1]]
    robot_point.set_data(x_vals[-1:], y_vals[-1:])  # CORRECCIÓN: usar listas, no números sueltos
    path_line.set_data(x_vals, y_vals)
    return robot_point, path_line

ani = animation.FuncAnimation(fig, update, frames=len(trayectoria),
                              init_func=init, blit=True, interval=300)

plt.close(fig)
HTML(ani.to_jshtml())